name: Worlds
main: com.github.neapovil.worlds.Worlds
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/worlds
depend:
  - CommandAPI
permissions:
  worlds.command:
    default: op
  worlds.broadcast:
    default: op
  worlds.command.admin:
    default: op
